---
- name: get mdt device info
  command: lsblk -f {{ lustre.mdt_device }}
  changed_when: false
  register: lsblk_mdt

- name: format mdt
  shell: >
    mkfs.lustre 
    --fsname=LustreFS --mgs --mdt
    --mountfsoptions="user_xattr,errors=remount-ro"
    --backfstype=ldiskfs
    --reformat {{ lustre.mdt_device }}
    --index 0
  when: not lsblk_mdt.stdout is search('LustreFS')

- name: create mdt mount directory
  file:
    path: /mnt/mgsmds
    state: directory

- name: mount mdt
  mount:
    path: /mnt/mgsmds
    src: '{{ lustre.mdt_device }}'
    opts: noatime,nodiratime,nobarrier
    passno: '2'
    state: mounted
    fstype: lustre

- name: set mdt params
  shell: |
    lctl set_param -P mdt.*-MDT0000.hsm_control=enabled
    lctl set_param -P mdt.*-MDT0000.hsm.default_archive_id=1
    lctl set_param mdt.*-MDT0000.hsm.max_requests={{ lustre.hsm_max_requests }}
    lctl set_param mdt.*-MDT0000.identity_upcall=NONE

# Enable Change log
- name: install robinhood-adm rpm
  yum:
    name:
      - https://azurehpc.azureedge.net/rpms/robinhood-adm-3.1.6-1.x86_64.rpm
    state: present

- name: enable chglogs for lustre
  command: rbh-config enable_chglogs LustreFS

# Enable chglogs on MDS for changelog reader
- name: check to cl2 exists
  shell: lctl get_param mdd.LustreFS-MDT0000.changelog_users | grep "cl2"
  register: cl2_exists
  ignore_errors: true

- name: enable cl2 user
  command: lctl --device LustreFS-MDT0000 changelog_register
  when: cl2_exists.stdout == ""
