---

- name: Add the Grafana YUM repository
  yum_repository:
    name: "grafana"
    description: "grafana"
    baseurl: "https://rpm.grafana.com"
    gpgkey: "https://rpm.grafana.com/gpg.key"
    gpgcheck: true
    state: present
    exclude: "*beta*"
    sslverify: 1
    sslcacert: "/etc/pki/tls/certs/ca-bundle.crt"
    timeout: 180

- include_tasks: install.yml
- include_tasks: configure.yml
- include_tasks: provisioning.yml

- name: Copy dashboards files
  copy:
    src: '{{role_path}}/dashboards'
    dest: '{{ grafana_paths_provisioning }}/dashboards'

- name: Start and enable the Grafana service
  service:
    name: grafana-server
    state: started
    enabled: true