---
httpd_auth:
- AuthType openid-connect
- Require valid-user
user_map_cmd: '{{authentication.user_map_cmd | default(None)}}' # "/opt/ood/ood_auth_map/bin/ood_auth_map.regex --regex=''^(\\w+)@microsoft.com$''"
# https://osc.github.io/ood-documentation/latest/reference/files/ood-portal-yml.html#ood-portal-generator-user-map-match
user_map_match: '{{authentication.user_map_match | default(None)}}' # '^([^@]+)@microsoft.com$'
logout_redirect: '/oidc?logout=https%3A%2F%2F{{ servername }}'
oidc_uri: /oidc
#oidc_provider_metadata_url: https://sts.windows.net/{{tenant_id}}/.well-known/openid-configuration
# setting ood_auth_openidc will create a separate configuration auth file for apache 
ood_auth_openidc:
  OIDCProviderMetadataURL: '{{authentication.ood_auth_openidc.OIDCProviderMetadataURL}}'
  OIDCClientID: '{{authentication.ood_auth_openidc.OIDCClientID}}'
  OIDCClientSecret: '{{ oidc_client_secret }}'
  OIDCRemoteUserClaim: '{{authentication.ood_auth_openidc.OIDCRemoteUserClaim}}'
  OIDCScope: '{{authentication.ood_auth_openidc.OIDCScope}}'
  OIDCCryptoPassphrase: '{{ oidc_client_secret }}'
  OIDCPassIDTokenAs: '{{authentication.ood_auth_openidc.OIDCPassIDTokenAs}}'
  OIDCPassRefreshToken: '{{authentication.ood_auth_openidc.OIDCPassRefreshToken}}'
  OIDCPassClaimsAs: '{{authentication.ood_auth_openidc.OIDCPassClaimsAs}}'
  OIDCStateMaxNumberOfCookies: '{{authentication.ood_auth_openidc.OIDCStateMaxNumberOfCookies | default([7, true])}}'
