#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#
name : Daily Deploy Only Bicep/Terraform/ARM

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * *" # At 0:10 UTC Daily

jobs:
  deploy_bicep_arm:
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        scheduler: ['slurm']
        home_type: ['azurefiles', 'anf']
        user_auth: ['local', 'ad']
        deploy_with: ['bicep']
        monitoring: ['grafana', 'none']
    uses: ./.github/workflows/z_deploy_only_callable.yml
    with:
      resource_group: 'AUTO_GENERATED'
      location: 'westeurope'
      scheduler: ${{ matrix.scheduler }}
      home_type: ${{ matrix.home_type }}
      user_auth: ${{ matrix.user_auth }}
      deploy_with: ${{ matrix.deploy_with }}
      monitoring: ${{ matrix.monitoring }}
      clean: 'true'
    secrets:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  deploy_tf:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        scheduler: ['slurm']
        home_type: ['anf']
        user_auth: ['local', 'ad']
        deploy_with: ['tf']
        monitoring: ['grafana', 'none']
    uses: ./.github/workflows/z_deploy_only_callable.yml
    with:
      resource_group: 'AUTO_GENERATED'
      location: 'westeurope'
      scheduler: ${{ matrix.scheduler }}
      home_type: ${{ matrix.home_type }}
      user_auth: ${{ matrix.user_auth }}
      deploy_with: ${{ matrix.deploy_with }}
      monitoring: ${{ matrix.monitoring }}
      clean: 'true'
    secrets:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
